<?php
/**
* @file
* A description of what your module does.
*/

require_once 'includes/webform.inc';  // specific webform enhancements for trading plattform
require_once 'includes/webform.node.inc'; // trading webform submission to node conversion implementation
require_once 'includes/webform.mail.inc'; // webform mail adaptations
require_once 'includes/proximity.action.inc'; // implements proximity item click action


/**
 * Implements hook_init().
 *
 * Redirects all node pages to the defined proximity container.
 */
function pxltrade_init() {
  if (drupal_is_front_page()) return;

  $pattern = '/^node\/\d+$/';
  if (preg_match($pattern, $_GET['q'])) {
    $param = str_replace('/', '-', $_GET['q']);
    drupal_goto('proximity-container-item/0/' . $param);
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function pxltrade_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module', 'pxltrade');
  if (isset($theme_registry['select_as_checkboxes'])) {
    $theme_registry['select_as_checkboxes']['includes'][] = $path . '/includes/bef.checkbox.theme';
    $theme_registry['select_as_checkboxes']['function'] = 'theme_filter_as_checkboxes';
  }
}


/**
 * Implements hook_theme().
 */
function pxltrade_theme() {
  return array(
    'pxltrade_bs_carousel' => array(
      'variables' => array(
        'interval' => '10000',
        'pause' => 0,
        'wrap' => 0,
        'keyboard' => 0,
        'indicators' => 1,
        'navigation' => 1,
        'id' => '',
        'items' => array(),
      ),
      'file' => 'templates/pxltrade-bs-carousel.vars.php',
      'template' => 'templates/pxltrade-bs-carousel',
    ),
    'pxltrade_delivery_confirmation' => array(
      'variables' => array(
        'node' => null,
        'sid' => null,
        'success' => true,
      ),
      'file' => 'templates/pxltrade-delivery-confirmation.vars.php',
      'template' => 'templates/pxltrade-delivery-confirmation',
    ),
  );
}


